/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreeRouteImport } from './routes/tree'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as OccasionsRouteImport } from './routes/occasions'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MyBlogRouteImport } from './routes/my-blog'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BusinessesRouteImport } from './routes/businesses'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogPostIdRouteImport } from './routes/blog_.$postId'

const TreeRoute = TreeRouteImport.update({
  id: '/tree',
  path: '/tree',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const OccasionsRoute = OccasionsRouteImport.update({
  id: '/occasions',
  path: '/occasions',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBlogRoute = MyBlogRouteImport.update({
  id: '/my-blog',
  path: '/my-blog',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesRoute = BusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPostIdRoute = BlogPostIdRouteImport.update({
  id: '/blog_/$postId',
  path: '/blog/$postId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/businesses': typeof BusinessesRoute
  '/contact': typeof ContactRoute
  '/family': typeof FamilyRoute
  '/gallery': typeof GalleryRoute
  '/my-blog': typeof MyBlogRoute
  '/news': typeof NewsRoute
  '/occasions': typeof OccasionsRoute
  '/our-story': typeof OurStoryRoute
  '/portal': typeof PortalRoute
  '/tree': typeof TreeRoute
  '/blog/$postId': typeof BlogPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/businesses': typeof BusinessesRoute
  '/contact': typeof ContactRoute
  '/family': typeof FamilyRoute
  '/gallery': typeof GalleryRoute
  '/my-blog': typeof MyBlogRoute
  '/news': typeof NewsRoute
  '/occasions': typeof OccasionsRoute
  '/our-story': typeof OurStoryRoute
  '/portal': typeof PortalRoute
  '/tree': typeof TreeRoute
  '/blog/$postId': typeof BlogPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/businesses': typeof BusinessesRoute
  '/contact': typeof ContactRoute
  '/family': typeof FamilyRoute
  '/gallery': typeof GalleryRoute
  '/my-blog': typeof MyBlogRoute
  '/news': typeof NewsRoute
  '/occasions': typeof OccasionsRoute
  '/our-story': typeof OurStoryRoute
  '/portal': typeof PortalRoute
  '/tree': typeof TreeRoute
  '/blog_/$postId': typeof BlogPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blog'
    | '/businesses'
    | '/contact'
    | '/family'
    | '/gallery'
    | '/my-blog'
    | '/news'
    | '/occasions'
    | '/our-story'
    | '/portal'
    | '/tree'
    | '/blog/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/blog'
    | '/businesses'
    | '/contact'
    | '/family'
    | '/gallery'
    | '/my-blog'
    | '/news'
    | '/occasions'
    | '/our-story'
    | '/portal'
    | '/tree'
    | '/blog/$postId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blog'
    | '/businesses'
    | '/contact'
    | '/family'
    | '/gallery'
    | '/my-blog'
    | '/news'
    | '/occasions'
    | '/our-story'
    | '/portal'
    | '/tree'
    | '/blog_/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BlogRoute: typeof BlogRoute
  BusinessesRoute: typeof BusinessesRoute
  ContactRoute: typeof ContactRoute
  FamilyRoute: typeof FamilyRoute
  GalleryRoute: typeof GalleryRoute
  MyBlogRoute: typeof MyBlogRoute
  NewsRoute: typeof NewsRoute
  OccasionsRoute: typeof OccasionsRoute
  OurStoryRoute: typeof OurStoryRoute
  PortalRoute: typeof PortalRoute
  TreeRoute: typeof TreeRoute
  BlogPostIdRoute: typeof BlogPostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tree': {
      id: '/tree'
      path: '/tree'
      fullPath: '/tree'
      preLoaderRoute: typeof TreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/occasions': {
      id: '/occasions'
      path: '/occasions'
      fullPath: '/occasions'
      preLoaderRoute: typeof OccasionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-blog': {
      id: '/my-blog'
      path: '/my-blog'
      fullPath: '/my-blog'
      preLoaderRoute: typeof MyBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses': {
      id: '/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof BusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$postId': {
      id: '/blog_/$postId'
      path: '/blog/$postId'
      fullPath: '/blog/$postId'
      preLoaderRoute: typeof BlogPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BlogRoute: BlogRoute,
  BusinessesRoute: BusinessesRoute,
  ContactRoute: ContactRoute,
  FamilyRoute: FamilyRoute,
  GalleryRoute: GalleryRoute,
  MyBlogRoute: MyBlogRoute,
  NewsRoute: NewsRoute,
  OccasionsRoute: OccasionsRoute,
  OurStoryRoute: OurStoryRoute,
  PortalRoute: PortalRoute,
  TreeRoute: TreeRoute,
  BlogPostIdRoute: BlogPostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
